---

- name: install basic package
  dnf: name={{ item }} state=present
  with_items:
     - vim
     - krb5-devel
     - krb5-workstation
     - git
     - tree
     - xchat

- name: copy the krb5 configuration file
  template: src=krb5/krb5.conf.j2 dest=/etc/krb5.conf
