---

- name: install basic package
  dnf: name={{ item }} state=present
  with_items:
     - vim
     - krb5-devel
     - krb5-workstation
     - git
     - tree
     - xchat

- name: copy the krb5 configuration file
  template: src=krb5/krb5.conf.j2 dest=/etc/krb5.conf

- name: check the ssh key exists
  stat: 
    path: ~/.ssh/{{ key_id }}
  register: ssh_key
  become: True
  become_method: su
  become_user: "{{ user }}"

- name: generate ssh key for user
  command: ssh-keygen -t rsa -f ~/.ssh/{{ key_id }} -N ''
  when: ssh_key.stat.exists == False
  become: True
  become_method: su
  become_user: "{{ user }}"
