---

- name: copy ovpn 
  command: "{{ item }}"
  with_items:
    - cp {{ ovpn_path }} /etc/NetworkManager/system-connections/
    - restorecon -RvF /etc/NetworkManager/system-connections
  tags: ovpn

- name: change ovpn file mode
  file:
    path: '/etc/NetworkManager/system-connections/{{ ovpn_file }}'
    mode: 0600
  tags: ovpn

- name: nmcli con reload
  command: "nmcli con reload"
  tags: ovpn
